#include "javascriptutil.h"

//コンストラクタ
JavascriptUtil::JavascriptUtil()
{}


//CSSカット検証
QString JavascriptUtil::css_cut()
{
    QString jsc = QString();
    jsc.append(u8"var d = document;");
    jsc.append(u8"var delarr = new Array();");
    jsc.append(u8"var links = d.getElementsByTagName(\"link\");");
    jsc.append(u8"for(var i=0; i<links.length; i++) {");
    jsc.append(u8"var link = links.item(i);");
    jsc.append(u8"var href = link.getAttribute(\"href\");");
    jsc.append(u8"if(is_css_file(href) || is_css_link(link)) {");
    jsc.append(u8"delarr.push(href);");
    jsc.append(u8"}");
    jsc.append(u8"}");
    jsc.append(u8"for(var i=0; i<delarr.length; i++) {");
    jsc.append(u8"var line = delarr[i];");
    jsc.append(u8"delete_link(line);");
    jsc.append(u8"}");
    jsc.append(u8"var tags = d.getElementsByTagName(\"*\");");
    jsc.append(u8"for(var i=0; i<tags.length; i++) {");
    jsc.append(u8"var tag = tags.item(i);");
    jsc.append(u8"var style = tag.getAttribute(\"style\");");
    jsc.append(u8"if(style !== null || style !== \"\") {");
    jsc.append(u8"tag.removeAttribute(\"style\");");
    jsc.append(u8"}");
    jsc.append(u8"}");
    jsc.append(u8"var styles = d.getElementsByTagName(\"style\");");
    jsc.append(u8"for(i=0; i<styles.length; i++) {");
    jsc.append(u8"var style = styles.item(i);");
    jsc.append(u8"style.textContent = null;");
    jsc.append(u8"}");
    jsc.append(u8"function is_css_file(href) {");
    jsc.append(u8"var pat = new RegExp(\".+\\.css\");");
    jsc.append(u8"if(pat.test(href)) return true;");
    jsc.append(u8"else return false;");
    jsc.append(u8"}");
    jsc.append(u8"function is_css_link(link) {");
    jsc.append(u8"if(link.hasAttribute(\"type\")) {");
    jsc.append(u8"var pat = new RegExp(\"text/css\");");
    jsc.append(u8"var type = link.getAttribute(\"type\");");
    jsc.append(u8"if(pat.test(type)) return true;");
    jsc.append(u8"else return false;");
    jsc.append(u8"} else {");
    jsc.append(u8"return false;");
    jsc.append(u8"}");
    jsc.append(u8"}");
    jsc.append(u8"function delete_link(line) {");
    jsc.append(u8"var lks = d.getElementsByTagName(\"link\");");
    jsc.append(u8"for(var j=0; j<lks.length; j++) {");
    jsc.append(u8"var lk = lks.item(j);");
    jsc.append(u8"var hf = lk.getAttribute(\"href\");");
    jsc.append(u8"if(hf === line) {");
    jsc.append(u8"lk.parentNode.removeChild(lk);");
    jsc.append(u8"break;");
    jsc.append(u8"}");
    jsc.append(u8"}");
    jsc.append(u8"}");
    return jsc;

}


//alt属性値検証
QString JavascriptUtil::image_alt()
{
    QString jsc = QString();
    jsc.append(u8"var fname_flg = true;");
    jsc.append(u8"var img = document.getElementsByTagName(\"img\");");
    jsc.append(u8"for(var i=0; i<img.length; i++) {");
    jsc.append(u8"var imgtag = img.item(i);");
    jsc.append(u8"imgtag.setAttribute(\"style\", \"border:1px solid red;\");");
    jsc.append(u8"var span_id = \"bkm-img-span-\" + i;");
    jsc.append(u8"var src_val = imgtag.getAttribute(\"src\");");
    jsc.append(u8"var fname = get_img_filename(src_val);");
    jsc.append(u8"var alt_val = imgtag.getAttribute(\"alt\");");
    jsc.append(u8"if(alt_val === null) {");
    jsc.append(u8"alt_val = alt_attr_from_dirtycode(imgtag);");
    jsc.append(u8"}");
    jsc.append(u8"var html_str = \"\";");
    jsc.append(u8"if(alt_attr_check(imgtag)) {");
    jsc.append(u8"html_str += \"alt: \" + alt_val;");
    jsc.append(u8"} else {");
    jsc.append(u8"html_str += \"alt属性がない\";");
    jsc.append(u8"}");
    jsc.append(u8"if(fname_flg) {");
    jsc.append(u8"if(html_str !== \"\") {");
    jsc.append(u8"html_str += \", filename: \" + fname;");
    jsc.append(u8"} else {");
    jsc.append(u8"html_str += \"filename: \" + fname;");
    jsc.append(u8"}");
    jsc.append(u8"}");
    jsc.append(u8"var css_txt = \"color:#fff;font-size:12px;padding:1px;background:#BF0000;\";");
    jsc.append(u8"var span = '<span id=\"' + span_id + '\" style=\"' + css_txt + '\">' + html_str + '</span>';");
    jsc.append(u8"imgtag.insertAdjacentHTML(\"beforebegin\", span);");
    jsc.append(u8"}");
    jsc.append(u8"tag_link_img();");
    jsc.append(u8"tag_area();");
    jsc.append(u8"function alt_attr_from_dirtycode(obj) {");
    jsc.append(u8"var ret = \"\";");
    jsc.append(u8"var imgtag = obj.outerHTML;");
    jsc.append(u8"var pt = new RegExp('(alt=\")(.*?)(\")');");
    jsc.append(u8"if(pt.test(imgtag)) {");
    jsc.append(u8"ret = imgtag.match(pt)[2];");
    jsc.append(u8"}");
    jsc.append(u8"return ret;");
    jsc.append(u8"}");
    jsc.append(u8"function get_img_filename(str) {");
    jsc.append(u8"var ret = \"\";");
    jsc.append(u8"var pat = new RegExp(\"(.+)\\/(.+\\.)(JPG|jpg|GIF|gif|PNG|png|BMP|bmp)$\");");
    jsc.append(u8"if(pat.test(str)) {");
    jsc.append(u8"var arr = str.match(pat);");
    jsc.append(u8"ret += arr[2] + arr[3];");
    jsc.append(u8"}");
    jsc.append(u8"return ret;");
    jsc.append(u8"}");
    jsc.append(u8"function alt_attr_check(imgtag) {");
    jsc.append(u8"var txt = imgtag.outerHTML;");
    jsc.append(u8"var pt1 = new RegExp('alt=\".*\"');");
    jsc.append(u8"var pt2 = new RegExp('alt=');");
    jsc.append(u8"if(pt1.test(txt) && pt2.test(txt)) return true;");
    jsc.append(u8"else return false;");
    jsc.append(u8"}");
    jsc.append(u8"function tag_link_img() {");
    jsc.append(u8"var ats = document.getElementsByTagName(\"a\");");
    jsc.append(u8"var css_txt = \"border:2px dotted red;\";");
    jsc.append(u8"for(var i=0; i<ats.length; i++) {");
    jsc.append(u8"var atag = ats.item(i);");
    jsc.append(u8"var imgs = atag.getElementsByTagName(\"img\");");
    jsc.append(u8"for(var j=0; j<imgs.length; j++) {");
    jsc.append(u8"var img = imgs.item(j);");
    jsc.append(u8"img.setAttribute(\"style\", css_txt);");
    jsc.append(u8"}");
    jsc.append(u8"}");
    jsc.append(u8"}");
    jsc.append(u8"function tag_area() {");
    jsc.append(u8"var area = document.getElementsByTagName(\"area\");");
    jsc.append(u8"for(var i=0; i<area.length; i++) {");
    jsc.append(u8"var areatag = area.item(i);");
    jsc.append(u8"var href_val = areatag.getAttribute(\"href\");");
    jsc.append(u8"var alt_val = areatag.getAttribute(\"alt\");");
    jsc.append(u8"var css_txt = \"color:#fff;font-size:12px;padding:1px;background:#7B0D0D;margin-right:2px;display:inline-block;border: 2px dotted #fdcf1b;\";");
    jsc.append(u8"var html_str = \"\";");
    jsc.append(u8"if(_alt_attr_check(areatag)) {");
    jsc.append(u8"html_str += \"alt: \" + alt_val;");
    jsc.append(u8"} else {");
    jsc.append(u8"html_str += \"alt属性がない\";");
    jsc.append(u8"}");
    jsc.append(u8"html_str += \", url: \" + href_val;");
    jsc.append(u8"var target_val = \"\";");
    jsc.append(u8"if(areatag.hasAttribute(\"target\")) {");
    jsc.append(u8"target_val = areatag.getAttribute(\"target\");");
    jsc.append(u8"} else {");
    jsc.append(u8"target_val = null;");
    jsc.append(u8"}");
    jsc.append(u8"if(target_val != null) {");
    jsc.append(u8"if(target_val == \"\") {");
    jsc.append(u8"html_str += `, <span style=\"background-color:#0f7136 !important;margin:2px;\">target属性有:(空)</span>`;");
    jsc.append(u8"} else {");
    jsc.append(u8"html_str += `, <span style=\"background-color:#0f7136 !important;margin:2px;\">target属性有:${target_val}</span>`;");
    jsc.append(u8"}");
    jsc.append(u8"}");
    jsc.append(u8"var span = `<span id=\"bkm-area-span-${i}\" style=\"${css_txt}\">area要素, ` + html_str + \"</span>\";");
    jsc.append(u8"areatag.insertAdjacentHTML(\"beforebegin\", span);");
    jsc.append(u8"}");
    jsc.append(u8"function _alt_attr_check(areatag) {");
    jsc.append(u8"var txt = areatag.outerHTML;");
    jsc.append(u8"var pt1 = new RegExp('alt=\".*\"');");
    jsc.append(u8"var pt2 = new RegExp('alt=');");
    jsc.append(u8"if(pt1.test(txt) && pt2.test(txt)) return true;");
    jsc.append(u8"else return false;");
    jsc.append(u8"}");
    jsc.append(u8"}");
    return jsc;
}


//target属性値検証
QString JavascriptUtil::target_attr()
{
    QString jsc = QString();
    jsc.append(u8"var ats = document.getElementsByTagName(\"a\");");
    jsc.append(u8"for(var i=0; i<ats.length; i++) {");
    jsc.append(u8"var atag = ats.item(i);");
    jsc.append(u8"var ataghtml = atag.outerHTML;");
    jsc.append(u8"ataghtml = _text_clean(ataghtml);");
    jsc.append(u8"if(_target_attr_check(ataghtml)) {");
    jsc.append(u8"var target_vl = atag.getAttribute(\"target\");");
    jsc.append(u8"var span_id = \"bkm-target-attr-span-\" + i;");
    jsc.append(u8"var span_html = (target_vl === \"\") ? \"target属性有:(空)\" : \"target属性有:\" + target_vl;");
    jsc.append(u8"var span_css = \"padding-right:5px;color:#fff;font-size:12px;padding:1px;background:#008000;border-radius:5px;\";");
    jsc.append(u8"var span = '<span id=\"' + span_id + '\" style=\"' + span_css + '\">' + span_html + '</span>';");
    jsc.append(u8"atag.insertAdjacentHTML(\"beforebegin\", span);");
    jsc.append(u8"}");
    jsc.append(u8"}");
    jsc.append(u8"function _target_attr_check(str) {");
    jsc.append(u8"var pt = new RegExp('target=\".*?\"');");
    jsc.append(u8"if(pt.test(str)) return true;");
    jsc.append(u8"else return false;");
    jsc.append(u8"}");
    jsc.append(u8"function _text_clean(str) {");
    jsc.append(u8"var ret = \"\";");
    jsc.append(u8"ret = str.replace(new RegExp(\"^ +\", \"mg\"), \"\");");
    jsc.append(u8"ret = ret.replace(new RegExp(\"\\t+\", \"mg\"), \"\");");
    jsc.append(u8"ret = ret.replace(new RegExp(\"(\\r\\n|\\r|\\n)\", \"mg\"), \"\");");
    jsc.append(u8"return str;");
    jsc.append(u8"}");
    return jsc;
}

//ページ構造検証
QString JavascriptUtil::semantic_check()
{
    QString jsc = QString();
    jsc.append(u8"function tag_paragraph() {");
    jsc.append(u8"var ps = document.getElementsByTagName(\"p\");");
    jsc.append(u8"for(var i=0; i<ps.length; i++) {");
    jsc.append(u8"var p = ps.item(i);");
    jsc.append(u8"p.setAttribute(\"style\", \"border:1px solid #3A87AD; position: relative;\");");
    jsc.append(u8"add_label(p, i, \"afterbegin\", \"#3A87AD\");");
    jsc.append(u8"}");
    jsc.append(u8"}");
    jsc.append(u8"function tag_heading() {");
    jsc.append(u8"var tags = [\"h1\", \"h2\", \"h3\", \"h4\", \"h5\", \"h6\"];");
    jsc.append(u8"var idx = tags.length;");
    jsc.append(u8"var in_funcs = new Array();");
    jsc.append(u8"for(var i=0; i<idx; i++) {");
    jsc.append(u8"var val = tags[i];");
    jsc.append(u8"in_funcs.push(make_funcs(val));");
    jsc.append(u8"}");
    jsc.append(u8"function make_funcs(tag) {");
    jsc.append(u8"return function() {");
    jsc.append(u8"var ts = document.getElementsByTagName(tag);");
    jsc.append(u8"for(var i=0; i<ts.length; i++) {");
    jsc.append(u8"var t = ts.item(i);");
    jsc.append(u8"t.setAttribute(\"style\", \"border:1px solid red; position: relative;\");");
    jsc.append(u8"add_label(t, i, \"afterbegin\", \"#B94A48\");");
    jsc.append(u8"}");
    jsc.append(u8"}");
    jsc.append(u8"}");
    jsc.append(u8"for(var i=0; i<idx; i++) {");
    jsc.append(u8"in_funcs[i]();");
    jsc.append(u8"}");
    jsc.append(u8"}");
    jsc.append(u8"function tag_br() {");
    jsc.append(u8"var brs = document.getElementsByTagName(\"br\");");
    jsc.append(u8"for(var i=0; i<brs.length; i++) {");
    jsc.append(u8"var br = brs.item(i);");
    jsc.append(u8"var css_txt = \"color:#fff;font-size:90%!important;padding:1px;border-radius:3px;\";");
    jsc.append(u8"var span = '<span id=\"bkm-br-span-' + i + '\" style=\"' + css_txt + 'background:#888888;\">&lt;br&gt;</span>';");
    jsc.append(u8"br.insertAdjacentHTML(\"beforebegin\", span);");
    jsc.append(u8"}");
    jsc.append(u8"}");
    jsc.append(u8"function tag_semantic() {");
    jsc.append(u8"var tags = [\"strong\", \"em\", \"address\", \"nav\", \"section\"];");
    jsc.append(u8"var idx = tags.length;");
    jsc.append(u8"var in_funcs = new Array();");
    jsc.append(u8"for(var i=0; i<idx; i++) {");
    jsc.append(u8"var val = tags[i];");
    jsc.append(u8"in_funcs.push(make_funcs(val));");
    jsc.append(u8"}");
    jsc.append(u8"function make_funcs(tag) {");
    jsc.append(u8"return function() {");
    jsc.append(u8"var ts = document.getElementsByTagName(tag);");
    jsc.append(u8"for(var i=0; i<ts.length; i++) {");
    jsc.append(u8"var t = ts.item(i);");
    jsc.append(u8"t.setAttribute(\"style\", \"border:1px solid #808080; position: relative;\");");
    jsc.append(u8"add_label(t, i, \"afterbegin\", \"#888888\");");
    jsc.append(u8"}");
    jsc.append(u8"}");
    jsc.append(u8"}");
    jsc.append(u8"for(var i=0; i<idx; i++) {");
    jsc.append(u8"in_funcs[i]();");
    jsc.append(u8"}");
    jsc.append(u8"}");
    jsc.append(u8"function tag_list() {");
    jsc.append(u8"var tags = [\"ul\", \"ol\", \"dl\", \"dt\", \"dd\"];");
    jsc.append(u8"var idx = tags.length;");
    jsc.append(u8"var in_funcs = new Array();");
    jsc.append(u8"for(var i=0; i<idx; i++) {");
    jsc.append(u8"var val = tags[i];");
    jsc.append(u8"in_funcs.push(make_funcs(val));");
    jsc.append(u8"}");
    jsc.append(u8"function make_funcs(tag) {");
    jsc.append(u8"return function() {");
    jsc.append(u8"var ts = document.getElementsByTagName(tag);");
    jsc.append(u8"for(var i=0; i<ts.length; i++) {");
    jsc.append(u8"var t = ts.item(i);");
    jsc.append(u8"t.setAttribute(\"style\", \"border:1px solid #468847; position: relative;\");");
    jsc.append(u8"add_label(t, i, \"afterbegin\", \"#468847\");");
    jsc.append(u8"}");
    jsc.append(u8"}");
    jsc.append(u8"}");
    jsc.append(u8"for(var i=0; i<idx; i++) {");
    jsc.append(u8"in_funcs[i]();");
    jsc.append(u8"}");
    jsc.append(u8"}");
    jsc.append(u8"function tag_table() {");
    jsc.append(u8"var in_funcs = [");
    jsc.append(u8"function() {");
    jsc.append(u8"var tbls = document.getElementsByTagName(\"table\");");
    jsc.append(u8"for(var i=0; i<tbls.length; i++) {");
    jsc.append(u8"var tbl = tbls.item(i);");
    jsc.append(u8"tbl.setAttribute(\"style\", \"border:2px solid red!important; position: relative;\");");
    jsc.append(u8"add_label(tbl, i, \"beforebegin\", \"#800000\");");
    jsc.append(u8"}");
    jsc.append(u8"for(var i=0; i<tbls.length; i++) {");
    jsc.append(u8"var tbl = tbls.item(i);");
    jsc.append(u8"var smry = tbl.getAttribute(\"summary\");");
    jsc.append(u8"var span = document.getElementById(\"bkm-table-span-\" + i);");
    jsc.append(u8"var now_label_text = span.innerHTML;");
    jsc.append(u8"var new_label_text = (smry === null) ? now_label_text : now_label_text + \", summary:\" + smry;");
    jsc.append(u8"span.innerHTML = new_label_text;");
    jsc.append(u8"}");
    jsc.append(u8"},");
    jsc.append(u8"function() {");
    jsc.append(u8"var cps = document.getElementsByTagName(\"caption\");");
    jsc.append(u8"for(var i=0; i<cps.length; i++) {");
    jsc.append(u8"var cp = cps.item(i);");
    jsc.append(u8"cp.setAttribute(\"style\", \"border:1px solid red!important; position: relative;\");");
    jsc.append(u8"add_label(cp, i, \"afterbegin\", \"#800000\");");
    jsc.append(u8"}");
    jsc.append(u8"},");
    jsc.append(u8"function() {");
    jsc.append(u8"var ths = document.getElementsByTagName(\"th\");");
    jsc.append(u8"for(var i=0; i<ths.length; i++) {");
    jsc.append(u8"var th = ths.item(i);");
    jsc.append(u8"th.setAttribute(\"style\", \"border:2px solid red!important; position: relative;\");");
    jsc.append(u8"add_label(th, i, \"afterbegin\", \"#800000\");");
    jsc.append(u8"}");
    jsc.append(u8"for(var i=0; i<ths.length; i++) {");
    jsc.append(u8"var th = ths.item(i);");
    jsc.append(u8"var scope = th.getAttribute(\"scope\");");
    jsc.append(u8"var span = document.getElementById(\"bkm-th-span-\" + i);");
    jsc.append(u8"var now_label_text = span.innerHTML;");
    jsc.append(u8"var new_label_text = (scope===null) ? now_label_text : now_label_text + \", scope:\" + scope;");
    jsc.append(u8"span.innerHTML = new_label_text;");
    jsc.append(u8"}");
    jsc.append(u8"}");
    jsc.append(u8"];");
    jsc.append(u8"for(var i=0; i<in_funcs.length; i++) {");
    jsc.append(u8"in_funcs[i]();");
    jsc.append(u8"}");
    jsc.append(u8"}");
    jsc.append(u8"function tag_empty_a() {");
    jsc.append(u8"var empas = document.querySelectorAll(\"a:empty, a span:empty\");");
    jsc.append(u8"var i = 0;");
    jsc.append(u8"for(var itm of empas) {");
    jsc.append(u8"var href_flg = null;");
    jsc.append(u8"if(!itm.hasAttribute(\"name\")) {");
    jsc.append(u8"var css_txt = \"color:#fff;font-size:90%!important;padding:1px;border-radius:3px;\";");
    jsc.append(u8"var span = '<span id=\"bkm-empry-a-span-' + i + '\" style=\"' + css_txt + 'background:#C000C0;\">空リンク有</span>';");
    jsc.append(u8"itm.insertAdjacentHTML(\"beforebegin\", span);");
    jsc.append(u8"i++;");
    jsc.append(u8"}");
    jsc.append(u8"}");
    jsc.append(u8"}");
    jsc.append(u8"function add_label(obj, cnt, pos, colorcode) {");
    jsc.append(u8"var tag_name = obj.tagName;");
    jsc.append(u8"tag_name = tag_name.toLowerCase();");
    jsc.append(u8"var span_id = \"bkm-\" + tag_name + \"-span-\" + cnt;");
    jsc.append(u8"var css_txt = \"color:#fff;font-size:90%!important;font-weight:normal!important;padding:1px;border-radius:3px;\";");
    jsc.append(u8"css_txt += 'background:' + colorcode + ';';");
    jsc.append(u8"var html_str = '&lt;' + tag_name + '&gt;';");
    jsc.append(u8"var span = '<span id=\"' + span_id + '\" style=\"' + css_txt + '\">' + html_str + '</span>';");
    jsc.append(u8"obj.insertAdjacentHTML(pos, span);");
    jsc.append(u8"}");
    jsc.append(u8"tag_paragraph();");
    jsc.append(u8"tag_heading();");
    jsc.append(u8"tag_br();");
    jsc.append(u8"tag_semantic();");
    jsc.append(u8"tag_list();");
    jsc.append(u8"tag_table();");
    jsc.append(u8"tag_empty_a();");
    return jsc;
}


//lang属性検証
QString JavascriptUtil::lang_attr()
{
    QString jsc = QString();
    jsc.append(u8"var alltags = document.getElementsByTagName(\"*\");");
    jsc.append(u8"var type = \"\";");
    jsc.append(u8"for(var i=0; i<alltags.length; i++) {");
    jsc.append(u8"var tag = alltags.item(i);");
    jsc.append(u8"var tag_name = tag.tagName.toLowerCase();");
    jsc.append(u8"if(tag.hasAttribute(\"lang\") || tag.hasAttribute(\"xml:lang\")) {");
    jsc.append(u8"if(tag.hasAttribute(\"lang\") && tag.hasAttribute(\"xml:lang\")) {");
    jsc.append(u8"type = \"all\";");
    jsc.append(u8"} else if(tag.hasAttribute(\"lang\") && !tag.hasAttribute(\"xml:lang\")) {");
    jsc.append(u8"type = \"lang-only\";");
    jsc.append(u8"} else if(!tag.hasAttribute(\"lang\") && tag.hasAttribute(\"xml:lang\")) {");
    jsc.append(u8"type = \"xml-lang-only\";");
    jsc.append(u8"}");
    jsc.append(u8"var lang_vl = \"\";");
    jsc.append(u8"var xml_lang_vl = \"\";");
    jsc.append(u8"if(type === \"all\") {");
    jsc.append(u8"lang_vl = tag.getAttribute(\"lang\");");
    jsc.append(u8"xml_lang_vl = tag.getAttribute(\"xml:lang\");");
    jsc.append(u8"} else if(type === \"lang-only\") {");
    jsc.append(u8"lang_vl = tag.getAttribute(\"lang\");");
    jsc.append(u8"} else if(type === \"xml-lang-only\") {");
    jsc.append(u8"xml_lang_vl = tag.getAttribute(\"xml:lang\");");
    jsc.append(u8"}");
    jsc.append(u8"var span_id = \"bkm-lang-attr-span-\" + i;");
    jsc.append(u8"var span_html = \"\";");
    jsc.append(u8"if(type === \"all\") {");
    jsc.append(u8"span_html = (lang_vl === \"\") ? \"lang属性有:(空)\" : \"lang属性有: \" + lang_vl;");
    jsc.append(u8"span_html += (xml_lang_vl === \"\") ? \" , xml:lang属性有:(空)\" : \" , xml:lang属性有: \" + xml_lang_vl;");
    jsc.append(u8"} else if(type === \"lang-only\") {");
    jsc.append(u8"span_html = (lang_vl === \"\") ? \"lang属性有:(空)\" : \"lang属性有: \" + lang_vl;");
    jsc.append(u8"} else if(type === \"xml-lang-only\") {");
    jsc.append(u8"span_html = (xml_lang_vl === \"\") ? \"xml:lang属性有:(空)\" : \"xml:lang属性有: \" + xml_lang_vl;");
    jsc.append(u8"}");
    jsc.append(u8"span_html = '&lt;' + tag.tagName.toLowerCase() + '&gt;要素 , ' + span_html;");
    jsc.append(u8"var span_css = \"padding-right:5px;color:#fff;font-size:13px;padding:1px;background:#008000;border-radius:5px;\";");
    jsc.append(u8"var span = '<span id=\"' + span_id + '\" style=\"' + span_css + '\">' + span_html + '</span>';");
    jsc.append(u8"if(tag_name === \"img\") {");
    jsc.append(u8"tag.insertAdjacentHTML(\"afterend\", span);");
    jsc.append(u8"} else {");
    jsc.append(u8"tag.insertAdjacentHTML(\"afterbegin\", span);");
    jsc.append(u8"}");
    jsc.append(u8"}");
    jsc.append(u8"}");
    return jsc;
}


//フォームラベルとtitle属性検証
QString JavascriptUtil::tag_label_and_title_attr()
{
    QString jsc = QString();
    jsc.append(u8"function tag_label_label() {");
    jsc.append(u8"var lbs = document.getElementsByTagName(\"label\");");
    jsc.append(u8"for(var i=0; i<lbs.length; i++) {");
    jsc.append(u8"var lb = lbs.item(i);");
    jsc.append(u8"lb.setAttribute(\"style\", \"border:1px solid #468847!important; position: relative;\");");
    jsc.append(u8"var span_html = \"\";");
    jsc.append(u8"var span_style = \"\";");
    jsc.append(u8"var span_id = \"bkm-label-span-\" + i;");
    jsc.append(u8"var type = \"\";");
    jsc.append(u8"if(lb.hasAttribute(\"for\")) {");
    jsc.append(u8"type = \"for-is-yes\";");
    jsc.append(u8"span_style = \"padding-right:5px;color:#fff;font-size:12px;padding:1px;background:#008000;border-radius:5px;\";");
    jsc.append(u8"} else {");
    jsc.append(u8"type = \"for-is-no\";");
    jsc.append(u8"span_style = \"padding-right:5px;color:#fff;font-size:12px;padding:1px;background:#C00000;border-radius:5px;\";");
    jsc.append(u8"}");
    jsc.append(u8"if(type === \"for-is-yes\") {");
    jsc.append(u8"var for_vl = lb.getAttribute(\"for\");");
    jsc.append(u8"span_html = (for_vl === \"\") ? \"for属性有:(空)\" : \"for属性有: \" + for_vl;");
    jsc.append(u8"span_html = '&lt;' + lb.tagName.toLowerCase() + '&gt; , ' + span_html;");
    jsc.append(u8"} else if(type === \"for-is-no\") {");
    jsc.append(u8"span_html = '&lt;' + lb.tagName.toLowerCase() + '&gt; , for属性なし';");
    jsc.append(u8"}");
    jsc.append(u8"var span  = '<span id=\"' + span_id + '\" style=\"' + span_style + '\">' + span_html + '</span>';");
    jsc.append(u8"lb.insertAdjacentHTML(\"afterbegin\", span);");
    jsc.append(u8"}");
    jsc.append(u8"}");
    jsc.append(u8"function tag_label_input() {");
    jsc.append(u8"var ips = document.getElementsByTagName(\"input\");");
    jsc.append(u8"for(var i=0; i<ips.length; i++) {");
    jsc.append(u8"var ip = ips.item(i);");
    jsc.append(u8"var typeattr = \"\";");
    jsc.append(u8"if(!ip.hasAttribute(\"type\")) {");
    jsc.append(u8"typeattr = \"text\";");
    jsc.append(u8"} else {");
    jsc.append(u8"typeattr = ip.getAttribute(\"type\");");
    jsc.append(u8"}");
    jsc.append(u8"if(typeattr === \"text\" || typeattr === \"radio\" || typeattr === \"checkbox\" || typeattr === \"password\") {");
    jsc.append(u8"var span_html = \"\";");
    jsc.append(u8"var span_style = \"\";");
    jsc.append(u8"var span_id = \"bkm-input-span-\" + i;");
    jsc.append(u8"ip.setAttribute(\"style\", \"border:1px solid blue; position: relative;\");");
    jsc.append(u8"var type = \"\";");
    jsc.append(u8"if(ip.hasAttribute(\"id\")) {");
    jsc.append(u8"type = \"id-yes\";");
    jsc.append(u8"span_style = \"padding-right:5px;color:#fff;font-size:12px;padding:1px;background:#3A87AD;border-radius:5px;\";");
    jsc.append(u8"} else {");
    jsc.append(u8"type = \"id-no\";");
    jsc.append(u8"span_style = \"padding-right:5px;color:#fff;font-size:12px;padding:1px;background:#C00000;border-radius:5px;\";");
    jsc.append(u8"}");
    jsc.append(u8"if(type === \"id-yes\") {");
    jsc.append(u8"var id_vl = ip.getAttribute(\"id\");");
    jsc.append(u8"span_html = (id_vl === \"\") ? \"id属性有:(空)\" : \"id属性有: \" + id_vl;");
    jsc.append(u8"} else if(type === \"id-no\") {");
    jsc.append(u8"span_html = \"id属性なし\";");
    jsc.append(u8"}");
    jsc.append(u8"var span  = '<span id=\"' + span_id + '\" style=\"' + span_style + '\">' + span_html + '</span>';");
    jsc.append(u8"ip.insertAdjacentHTML(\"beforebegin\", span);");
    jsc.append(u8"}");
    jsc.append(u8"}");
    jsc.append(u8"}");
    jsc.append(u8"function tag_label_textarea() {");
    jsc.append(u8"var tas = document.getElementsByTagName(\"textarea\");");
    jsc.append(u8"for(var i=0; i<tas.length; i++) {");
    jsc.append(u8"var ta = tas.item(i);");
    jsc.append(u8"ta.setAttribute(\"style\", \"border:1px solid blue; position: relative;\");");
    jsc.append(u8"var span_html = \"\";");
    jsc.append(u8"var span_style = \"\";");
    jsc.append(u8"var span_id = \"bkm-textarea-span-\" + i;");
    jsc.append(u8"var type = \"\";");
    jsc.append(u8"if(ta.hasAttribute(\"id\")) {");
    jsc.append(u8"type = \"id-yes\";");
    jsc.append(u8"span_style = \"padding-right:5px;color:#fff;font-size:12px;padding:1px;background:#3A87AD;border-radius:5px;\";");
    jsc.append(u8"} else {");
    jsc.append(u8"type = \"id-no\";");
    jsc.append(u8"span_style = \"padding-right:5px;color:#fff;font-size:12px;padding:1px;background:#C00000;border-radius:5px;\";");
    jsc.append(u8"}");
    jsc.append(u8"if(type === \"id-yes\") {");
    jsc.append(u8"var id_vl = ta.getAttribute(\"id\");");
    jsc.append(u8"span_html = (id_vl === \"\") ? \"id属性有:(空)\" : \"id属性有: \" + id_vl;");
    jsc.append(u8"} else if(type === \"id-no\") {");
    jsc.append(u8"span_html = \"id属性なし\";");
    jsc.append(u8"}");
    jsc.append(u8"var span  = '<span id=\"' + span_id + '\" style=\"' + span_style + '\">' + span_html + '</span>';");
    jsc.append(u8"ta.insertAdjacentHTML(\"beforebegin\", span);");
    jsc.append(u8"}");
    jsc.append(u8"}");
    jsc.append(u8"function tag_label_select() {");
    jsc.append(u8"var sls = document.getElementsByTagName(\"select\");");
    jsc.append(u8"for(var i=0; i<sls.length; i++) {");
    jsc.append(u8"var sl = sls.item(i);");
    jsc.append(u8"sl.setAttribute(\"style\", \"border:1px solid blue; position: relative;\");");
    jsc.append(u8"var span_html = \"\";");
    jsc.append(u8"var span_style = \"\";");
    jsc.append(u8"var span_id = \"bkm-select-span-\" + i;");
    jsc.append(u8"var type = \"\";");
    jsc.append(u8"if(sl.hasAttribute(\"id\")) {");
    jsc.append(u8"type = \"id-yes\";");
    jsc.append(u8"span_style = \"padding-right:5px;color:#fff;font-size:12px;padding:1px;background:#3A87AD;border-radius:5px;\";");
    jsc.append(u8"} else {");
    jsc.append(u8"type = \"id-no\";");
    jsc.append(u8"span_style = \"padding-right:5px;color:#fff;font-size:12px;padding:1px;background:#C00000;border-radius:5px;\";");
    jsc.append(u8"}");
    jsc.append(u8"if(type === \"id-yes\") {");
    jsc.append(u8"var id_vl = sl.getAttribute(\"id\");");
    jsc.append(u8"span_html = (id_vl === \"\") ? \"id属性有:(空)\" : \"id属性有: \" + id_vl;");
    jsc.append(u8"} else if(type === \"id-no\") {");
    jsc.append(u8"span_html = \"id属性なし\";");
    jsc.append(u8"}");
    jsc.append(u8"var span  = '<span id=\"' + span_id + '\" style=\"' + span_style + '\">' + span_html + '</span>';");
    jsc.append(u8"sl.insertAdjacentHTML(\"beforebegin\", span);");
    jsc.append(u8"}");
    jsc.append(u8"}");
    jsc.append(u8"function tag_title_attr() {");
    jsc.append(u8"var tags = [\"a\", \"input\", \"textarea\", \"select\", \"iframe\"];");
    jsc.append(u8"var idx = tags.length;");
    jsc.append(u8"var in_funcs = new Array();");
    jsc.append(u8"for(var i=0; i<idx; i++) {");
    jsc.append(u8"var val = tags[i];");
    jsc.append(u8"in_funcs.push(make_funcs(val));");
    jsc.append(u8"}");
    jsc.append(u8"function make_funcs(tag) {");
    jsc.append(u8"return function() {");
    jsc.append(u8"var ts = document.getElementsByTagName(tag);");
    jsc.append(u8"for(var i=0; i<ts.length; i++) {");
    jsc.append(u8"var t = ts.item(i);");
    jsc.append(u8"var typeattr = \"\";");
    jsc.append(u8"var tag_name = t.tagName.toLowerCase();");
    jsc.append(u8"if(tag_name === \"input\") {");
    jsc.append(u8"if(!t.hasAttribute(\"type\")) {");
    jsc.append(u8"typeattr = \"text\";");
    jsc.append(u8"} else {");
    jsc.append(u8"typeattr = t.getAttribute(\"type\");");
    jsc.append(u8"}");
    jsc.append(u8"if(typeattr === \"text\" || typeattr === \"radio\" || typeattr === \"checkbox\" || typeattr === \"password\") {");
    jsc.append(u8"var span_html = \"\";");
    jsc.append(u8"var span_style = \"\";");
    jsc.append(u8"var span_id = \"bkm-title-attr-span-\" + i;");
    jsc.append(u8"var type = \"\";");
    jsc.append(u8"if(t.hasAttribute(\"title\")) {");
    jsc.append(u8"type = \"title-yes\";");
    jsc.append(u8"span_style = \"padding-right:5px;color:#fff;font-size:12px;padding:1px;background:#008000;border-radius:5px;\";");
    jsc.append(u8"} else {");
    jsc.append(u8"type = \"title-no\";");
    jsc.append(u8"span_style = \"padding-right:5px;color:#fff;font-size:12px;padding:1px;background:#C00000;border-radius:5px;\";");
    jsc.append(u8"}");
    jsc.append(u8"if(type === \"title-yes\") {");
    jsc.append(u8"var title_vl = t.getAttribute(\"title\");");
    jsc.append(u8"span_html = (title_vl === \"\") ? \"title属性有:(空)\" : \"title属性有: \" + title_vl;");
    jsc.append(u8"} else if(type === \"title-no\") {");
    jsc.append(u8"span_html = \"title属性なし\";");
    jsc.append(u8"}");
    jsc.append(u8"var span  = '<span id=\"' + span_id + '\" style=\"' + span_style + '\">' + span_html + '</span>';");
    jsc.append(u8"t.insertAdjacentHTML(\"beforebegin\", span);");
    jsc.append(u8"}");
    jsc.append(u8"} else if(tag_name === \"textarea\" || tag_name === \"select\") {");
    jsc.append(u8"var span_html = \"\";");
    jsc.append(u8"var span_style = \"\";");
    jsc.append(u8"var span_id = \"bkm-title-attr-span-\" + i;");
    jsc.append(u8"var type = \"\";");
    jsc.append(u8"if(t.hasAttribute(\"title\")) {");
    jsc.append(u8"type = \"title-yes\";");
    jsc.append(u8"span_style = \"padding-right:5px;color:#fff;font-size:12px;padding:1px;background:#008000;border-radius:5px;\";");
    jsc.append(u8"} else {");
    jsc.append(u8"type = \"title-no\";");
    jsc.append(u8"span_style = \"padding-right:5px;color:#fff;font-size:12px;padding:1px;background:#C00000;border-radius:5px;\";");
    jsc.append(u8"}");
    jsc.append(u8"if(type === \"title-yes\") {");
    jsc.append(u8"var title_vl = t.getAttribute(\"title\");");
    jsc.append(u8"span_html = (title_vl === \"\") ? \"title属性有:(空)\" : \"title属性有: \" + title_vl;");
    jsc.append(u8"} else if(type === \"title-no\") {");
    jsc.append(u8"span_html = \"title属性なし\";");
    jsc.append(u8"}");
    jsc.append(u8"var span  = '<span id=\"' + span_id + '\" style=\"' + span_style + '\">' + span_html + '</span>';");
    jsc.append(u8"t.insertAdjacentHTML(\"beforebegin\", span);");
    jsc.append(u8"} else if(tag_name === \"iframe\") {");
    jsc.append(u8"var span_html = \"\";");
    jsc.append(u8"var span_style = \"\";");
    jsc.append(u8"span_html = tag_name + \"要素, \";");
    jsc.append(u8"var span_id = \"bkm-title-attr-span-\" + i;");
    jsc.append(u8"if(t.hasAttribute(\"title\")) {");
    jsc.append(u8"var title_vl = t.getAttribute(\"title\");");
    jsc.append(u8"span_html += (title_vl === \"\") ? \"title属性有:(空)\" : \"title属性有: \" + title_vl;");
    jsc.append(u8"span_style = \"padding-right:5px;color:#fff;font-size:12px;padding:1px;background:#008000;border-radius:5px;\";");
    jsc.append(u8"} else {");
    jsc.append(u8"span_html += \"title属性なし\";");
    jsc.append(u8"span_style = \"padding-right:5px;color:#fff;font-size:12px;padding:1px;background:#C00000;border-radius:5px;\";");
    jsc.append(u8"}");
    jsc.append(u8"var span  = '<span id=\"' + span_id + '\" style=\"' + span_style + '\">' + span_html + '</span>';");
    jsc.append(u8"t.insertAdjacentHTML(\"beforebegin\", span);");
    jsc.append(u8"} else {");
    jsc.append(u8"var span_html = \"\";");
    jsc.append(u8"var span_style = \"\";");
    jsc.append(u8"var span_id = \"bkm-title-attr-span-\" + i;");
    jsc.append(u8"if(t.hasAttribute(\"title\")) {");
    jsc.append(u8"var title_vl = t.getAttribute(\"title\");");
    jsc.append(u8"span_style = \"padding-right:5px;color:#fff;font-size:12px;padding:1px;background:#008000;border-radius:5px;\";");
    jsc.append(u8"span_html = (title_vl === \"\") ? \"title属性有:(空)\" : \"title属性有: \" + title_vl;");
    jsc.append(u8"var span  = '<span id=\"' + span_id + '\" style=\"' + span_style + '\">' + span_html + '</span>';");
    jsc.append(u8"t.insertAdjacentHTML(\"beforebegin\", span);");
    jsc.append(u8"}");
    jsc.append(u8"}");
    jsc.append(u8"}");
    jsc.append(u8"}");
    jsc.append(u8"}");
    jsc.append(u8"for(var i=0; i<idx; i++) {");
    jsc.append(u8"in_funcs[i]();");
    jsc.append(u8"}");
    jsc.append(u8"}");
    jsc.append(u8"tag_label_label();");
    jsc.append(u8"tag_label_input();");
    jsc.append(u8"tag_label_textarea();");
    jsc.append(u8"tag_label_select();");
    jsc.append(u8"tag_title_attr();");
    return jsc;
}


//ドキュメントリンク検証
QString JavascriptUtil::document_link()
{
    QString jsc = QString();
    jsc.append(u8"var regx_arr = new Array();");
    jsc.append(u8"var exts = [\"pdf\", \"doc\", \"docx\", \"xls\", \"xlsx\", \"jtd\", \"ppt\", \"pptx\", \"csv\", \"odt\", \"ods\", \"odp\", \"zip\"];");
    jsc.append(u8"for(var i=0; i<exts.length; i++) {");
    jsc.append(u8"var ext = exts[i];");
    jsc.append(u8"var in_regx = new RegExp(\"(.*\\/*)(.+\\.)(\" + ext + \")$\");");
    jsc.append(u8"regx_arr.push(in_regx);");
    jsc.append(u8"}");
    jsc.append(u8"var ats = document.getElementsByTagName(\"a\");");
    jsc.append(u8"for(var i=0; i<ats.length; i++) {");
    jsc.append(u8"var atag = ats.item(i);");
    jsc.append(u8"if(atag.hasAttribute(\"href\")) {");
    jsc.append(u8"var href_vl = atag.getAttribute(\"href\");");
    jsc.append(u8"if(is_doc_link(regx_arr, href_vl)) {");
    jsc.append(u8"var cr_ext = get_document_type(regx_arr, href_vl);");
    jsc.append(u8"var span_id = \"bkm-isdocument-span-\" + i;");
    jsc.append(u8"var span_html = \"Fileリンク: \" + cr_ext;");
    jsc.append(u8"span_html += \", filename: \" + get_filename(cr_ext, href_vl);");
    jsc.append(u8"var span_css = \"padding-right:5px;color:#fff;font-size:12px;padding:1px;background:#C000C0;border-radius:5px;\";");
    jsc.append(u8"var span = '<span id=\"' + span_id + '\" style=\"' + span_css + '\">' + span_html + '</span>';");
    jsc.append(u8"atag.insertAdjacentHTML(\"beforebegin\", span);");
    jsc.append(u8"} else if(is_premium_pdf_link(href_vl)) {");
    jsc.append(u8"var span_id = \"bkm-isdocument-span-\" + i;");
    jsc.append(u8"var span_html = \"Fileリンクの可能性有: PDF\";");
    jsc.append(u8"var span_css = \"padding-right:5px;color:#fff;font-size:12px;padding:1px;background:#C000C0;border-radius:5px;\";");
    jsc.append(u8"var span = '<span id=\"' + span_id + '\" style=\"' + span_css + '\">' + span_html + '</span>';");
    jsc.append(u8"atag.insertAdjacentHTML(\"beforebegin\", span);");
    jsc.append(u8"}");
    jsc.append(u8"}");
    jsc.append(u8"}");
    jsc.append(u8"function get_filename(ext, str) {");
    jsc.append(u8"var ret = \"\";");
    jsc.append(u8"var pt = new RegExp(\"(^\\/.+\\/|^\\.+.+\\/|.+\\/|.*)(\\/*)(.+)(\\.)(\" + ext + \"|\" + ext.toLowerCase() + \")$\");");
    jsc.append(u8"if(pt.test(str)) {");
    jsc.append(u8"var arr = str.match(pt);");
    jsc.append(u8"ret = arr[3] + arr[4] + arr[5];");
    jsc.append(u8"}");
    jsc.append(u8"return ret;");
    jsc.append(u8"}");
    jsc.append(u8"function is_premium_pdf_link(str) {");
    jsc.append(u8"str = str.toLowerCase();");
    jsc.append(u8"var pt = new RegExp(/(\\.pdf#|\\.pdf\\?)/);");
    jsc.append(u8"if(pt.test(str)) return true;");
    jsc.append(u8"else return false;");
    jsc.append(u8"}");
    jsc.append(u8"function is_doc_link(arr, str) {");
    jsc.append(u8"var flag = false;");
    jsc.append(u8"for(var i=0; i<arr.length; i++) {");
    jsc.append(u8"var aval = arr[i];");
    jsc.append(u8"if(aval.test(str)) {");
    jsc.append(u8"flag = true;");
    jsc.append(u8"break;");
    jsc.append(u8"}");
    jsc.append(u8"}");
    jsc.append(u8"return flag;");
    jsc.append(u8"}");
    jsc.append(u8"function get_document_type(arr, str) {");
    jsc.append(u8"var ret = \"\";");
    jsc.append(u8"for(var i=0; i<arr.length; i++) {");
    jsc.append(u8"var aval = arr[i];");
    jsc.append(u8"if(aval.test(str)) {");
    jsc.append(u8"ret = str.match(aval)[3];");
    jsc.append(u8"break;");
    jsc.append(u8"}");
    jsc.append(u8"}");
    jsc.append(u8"ret = ret.toUpperCase();");
    jsc.append(u8"return ret;");
    jsc.append(u8"}");
    return jsc;
}


//フォーカス検証
QString JavascriptUtil::super_focus()
{
    QString jsc = QString();
    jsc.append(u8"var hd = document.getElementsByTagName(\"head\")[0];");
    jsc.append(u8"var elm = document.createElement(\"style\");");
    jsc.append(u8"elm.setAttribute(\"type\", \"text/css\");");
    jsc.append(u8"elm.id = \"bkmk-super-focus-style-tag\";");
    jsc.append(u8"elm.textContent = \"*:focus,*:active {opacity: 0.2;filter:contrast(300%);}\";");
    jsc.append(u8"hd.appendChild(elm);");
    return jsc;
}


//WAI-ARIA属性検証
QString JavascriptUtil::wai_aria_attr()
{
    QString jsc = QString();
    jsc.append(u8"function tag_with_role_attr() {");
    jsc.append(u8"var elm = document.getElementsByTagName(\"*\");");
    jsc.append(u8"for(var i=0; i<elm.length; i++) {");
    jsc.append(u8"var el = elm.item(i);");
    jsc.append(u8"if(el.hasAttribute(\"role\")) {");
    jsc.append(u8"var attr_text = el.getAttribute(\"role\");");
    jsc.append(u8"el.setAttribute(\"style\", \"border:2px dotted #008080!important; position: relative;\");");
    jsc.append(u8"add_label(el, i, \"#279A9A\", 'role: ' + attr_text);");
    jsc.append(u8"}");
    jsc.append(u8"}");
    jsc.append(u8"}");
    jsc.append(u8"function tag_with_aria_attr() {");
    jsc.append(u8"var elm = document.getElementsByTagName(\"*\");");
    jsc.append(u8"var pt = new RegExp(/aria-.*/mg);");
    jsc.append(u8"for(var i=0; i<elm.length; i++) {");
    jsc.append(u8"var el = elm.item(i);");
    jsc.append(u8"var ret = \"\";");
    jsc.append(u8"var flg = false;");
    jsc.append(u8"var atts = el.attributes;");
    jsc.append(u8"for(var j=0; j<atts.length; j++) {");
    jsc.append(u8"var att = atts[j];");
    jsc.append(u8"if(pt.test(att.name)) {");
    jsc.append(u8"flg = true;");
    jsc.append(u8"ret += att.name + \": \" + att.value + \", \";");
    jsc.append(u8"}");
    jsc.append(u8"}");
    jsc.append(u8"if(flg == true) {");
    jsc.append(u8"add_label(el, i, \"#945E0E\", ret);");
    jsc.append(u8"}");
    jsc.append(u8"}");
    jsc.append(u8"}");
    jsc.append(u8"function tag_with_tabindex_attr() {");
    jsc.append(u8"var elm = document.getElementsByTagName(\"*\");");
    jsc.append(u8"var pt = new RegExp(/tabindex/mg);");
    jsc.append(u8"for(var i=0; i<elm.length; i++) {");
    jsc.append(u8"var el = elm.item(i);");
    jsc.append(u8"var ret = \"\";");
    jsc.append(u8"var flg = false;");
    jsc.append(u8"var atts = el.attributes;");
    jsc.append(u8"for(var j=0; j<atts.length; j++) {");
    jsc.append(u8"var att = atts[j];");
    jsc.append(u8"if(pt.test(att.name)) {");
    jsc.append(u8"flg = true;");
    jsc.append(u8"ret += att.name + \": \" + att.value + \", \";");
    jsc.append(u8"}");
    jsc.append(u8"}");
    jsc.append(u8"if(flg == true) {");
    jsc.append(u8"add_label(el, i, \"#C00000\", ret);");
    jsc.append(u8"}");
    jsc.append(u8"}");
    jsc.append(u8"}");
    jsc.append(u8"function add_label(obj, cnt, colorcode, add_text) {");
    jsc.append(u8"var tag_name = obj.tagName;");
    jsc.append(u8"tag_name = tag_name.toLowerCase();");
    jsc.append(u8"var span_id = \"bkm-\" + tag_name + \"-span-\" + cnt;");
    jsc.append(u8"var css_txt = \"color:#fff;font-size:90%!important;font-weight:normal!important;padding:1px;border-radius:3px;\";");
    jsc.append(u8"css_txt += 'background:' + colorcode + ';';");
    jsc.append(u8"var html_str = tag_name + '要素, ' + add_text;");
    jsc.append(u8"var span = '<span id=\"' + span_id + '\" style=\"' + css_txt + '\">' + html_str + '</span>';");
    jsc.append(u8"var addelm = document.createElement(\"span\");");
    jsc.append(u8"addelm.style.cssText = css_txt;");
    jsc.append(u8"addelm.innerHTML = span;");
    jsc.append(u8"obj.prepend(addelm);");
    jsc.append(u8"}");
    jsc.append(u8"tag_with_role_attr();");
    jsc.append(u8"tag_with_aria_attr();");
    jsc.append(u8"tag_with_tabindex_attr();");
    return jsc;
}
